### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nox** [image-rs/image-tiff#60]
It would be nice of you to release a new version with num-derive 0.3 so that downstream users can gradually get rid of syn 0.15 in their crate graph.

**Comment by JohnTitor** [comment]
cc: @HeroicKatora, could you make a new release?

**Comment by HeroicKatora** [comment]
There has been commit #3b85b68ae957e15e1e0609ea5368e849fdde9172 which is strictly speaking SemVer breaking. It adds a bunch of enum variants to `pub` types. From their use and definition it may have been somewhat obvious that these are intended to be non-exhaustive—they list a set of known, standardized identifiers—but the documentation didn't say so (in fact there is none) and they are a potential hazard. Is that an acceptable risk?

* Yes, release anyways :+1:
* No, revert the commit, do the release, re-apply the commit :-1:

Some input via respective reactions is appreciated.

**Comment by nox** [comment]
There is no acceptable risk here, please make a breaking bump. Why would you want to revert anything? Both `tiff` and `image` can just do a breaking bump.

**Comment by nox** [comment]
While at it, you could also just move the `ifd` stuff to its own crate, and make it an implementation detail in `tiff`, so that additional enum variants in any of the low-level blocks of `ifd` don't lead to a breaking change in the `tiff` crate.

**Comment by HeroicKatora** [comment]
> Why would you want to revert anything? Both tiff and image can just do a breaking bump.

I think I slightly misunderstood the motivation, I thought it was very important that this were a *non SemVer breaking* release. Then bumping the major version of `tiff` is certainly the better solution, after explicitely marking the `enum` as non-exhaustive and addressing #59 in the process.

However, it is somewhat more difficult to 'just do a breaking bump of `image`' and it feels off since it doesn't even use any of the internal affected. There's still a large portion that uses *previous* major releases and don't get performance improvements, bugfix and *soundness* fixes. Hence, I must object to a breaking release in that crate for the sole reason of improving the dependency graph in one of the decoders. I'd be slightly more open to it if it were the last occurrance.

So, considering the above some engineering is required. Since the breaking changes to `tiff` did not do any bug fixes it seems most useful to make a `0.3.2` release without them, that's what the above comment tries to outline with reverting, releasing, re-applying.

**Comment by HeroicKatora** [comment]
@nox What is the best course of action boils down to: Are you fine with waiting for `image = 0.23` until the changes are in or not?

**Comment by nox** [comment]
This is no pressing matter, take your time, no worries.

**Comment by jbg** [comment]
Couldn't you just branch off a maintenance branch for v0.3.x, merge the num-derive dep update into that and do a minor release from it, then carry on with development towards v0.4.0 at whatever pace desired?

**Comment by nox** [comment]
> Couldn't you just branch off a maintenance branch for v0.3.x, merge the num-derive dep update into that and do a minor release from it, then carry on with development towards v0.4.0 at whatever pace desired?

No, bumping `num-derive` increases the minimum Rust version that this crate works with and is thus a breaking change.

**Comment by jbg** [comment]
Oh, I see, I thought the only breaking change was the extra enum variants in pub types. FWIW, there are direct users of `tiff` such as myself that would appreciate a new release (even a breaking one) even if `image` won't use it immediately.
